### ISSUE TITLE
Open issues with manual

### ISSUE THREAD

**Issue by gertingold** [michael-hartmann/caps#122]
Rereading the manual, I found the following open issues which should be addressed in one way or the other before submission:

- [X] The manual contains different version numbers (0.4.2 on the title page and 0.4.3 in the listings). Before fixing this, we should decide whether in view of the submission, we want to go to 1.0. (resolved by #123 and #126, sticking to 0.4.3)
- [x] Is the reference to Emig et al. in the context of plane-cylinder really the appropriate one? (fixed by #124)
- [X] Is it ok to leave local computer information in the manual? (addressed in #127)
- [X] The syntax highlighting in some cases seems a bit odd. For example, on page 5, the argument of `-n` is highlighted but not the other numerical parameters. Overall, the highlighting seems pretty inconsistent and in most cases rather useless. Should we get rid of the highlighting or rather keep it? (fixed by #125)

I can do the changes once it is decided what to change or keep.
